/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Blue_Stone(props) {
  const { nodes, materials } = useGLTF('/explore/assets/models/blue_stone.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal_low002.geometry}
        material={materials.Crystal}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.012}
      />
    </group>
  )
}

useGLTF.preload('/explore/assets/models/blue_stone.glb')